### ISSUE TITLE
Support .dotfiles repository to allows for user-specific customization

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/roadmap#21]
We are supporting user-specific vscode settings and extensions, that add on top of the shared project-level configuration that is version in git repos. 
Allowing users to also inject a .dotfile repo on workspace start will allow further user-level customizations such as special shell configuration etc.
See https://github.com/gitpod-io/gitpod/issues/5198

**Comment by Siddhant-K-code** [comment]
For the Context, we are talking about `.vscode`  for all the preferences of a particular project?

**Comment by gtsiolis** [comment]
Hey everyone! FYI, we've recently shipped the first iteration of the `.dotfiles` support for workspaces, see https://github.com/gitpod-io/gitpod/issues/5198, https://github.com/gitpod-io/gitpod/pull/7337, and [relevant RFC](https://gitpod.notion.site/dotfiles-in-Gitpod-workspaces-b46b8723e9fe4efdbede72daa311961f) on how this works. 🔖 

It should be relatively straightforward to use this feature. In dashboard [`/preferences`](https://gitpod.io/preferences) add a repository URL that includes dotfiles. Gitpod will clone and install your dotfiles for every new workspace.

Follow up issues include :a: adding some relevant documentation (https://github.com/gitpod-io/website/issues/1407 Cc @jldec) and :b: improving the user experience of selecting a repository (https://github.com/gitpod-io/gitpod/issues/7385) from just having a text input for the repository URL. 🗺️ 

Cc @Siddhant-K-code @bigint @theflyingcodr @schickling @zpthree @trumbitta @vnsys

**Comment by apolopena** [comment]
How will this affect projects that already have thier own `.vscode/settings.json` file. Will it overwrite the file or skip over it?

**Comment by csweichel** [comment]
@apolopena That very much depends on what's in your dotfile repo. If there's no install script, but a `.vscode/settings.json` file in the dotfile repo, the dotfile repo's version would take precedence.

However, an install script could attempt to merge the `settings.json` files.

**Comment by apolopena** [comment]
> @apolopena That very much depends on what's in your dotfile repo. If there's no install script, but a `.vscode/settings.json` file in the dotfile repo, the dotfile repo's version would take precedence.
> 
> However, an install script could attempt to merge the `settings.json` files.

Then won't this feature will potentially break any project that parses the users environment via a script in the project repo? There really should be some way to override this behavior from the project level.
