### ISSUE TITLE
Self-Hosted Installer for Azure Kubernetes Service (AKS)

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/roadmap#24]
Provide documentation and scripts that enables anyone to install and update Gitpod Self-Hosted on AKS.

**Comment by svenefftinge** [comment]
see https://github.com/gitpod-io/gitpod-azure-aks-guide

**Comment by ghuntley** [comment]
This has shipped.

https://www.gitpod.io/docs/self-hosted/latest/installation
